# Generated by Django 4.1.7 on 2023-05-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjcodinggame_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.TextField(default='https://storage.googleapis.com/pod_public/1300/160041.jpg'),
        ),
    ]
