# Generated by Django 4.1.7 on 2023-05-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjcodinggame_app', '0002_alter_user_level_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.TextField(default='https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/c6238c0f-106f-4e4c-bf1c-00360465ae97/dea5apw-470c6b8a-1e26-49f9-9a4a-09d35e610734.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2M2MjM4YzBmLTEwNmYtNGU0Yy1iZjFjLTAwMzYwNDY1YWU5N1wvZGVhNWFwdy00NzBjNmI4YS0xZTI2LTQ5ZjktOWE0YS0wOWQzNWU2MTA3MzQucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.amOe7SO7CiBRu77meLkUaki_JeQ0Nz5XlZL_BWpTGuU'),
        ),
    ]
